# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9ce494a070a1979cd912bf029067e34fd756779d94ae71fa338ac21175f29d0239e583ee06a6f5c50887016ab0f56e14999d5a504f9d81e9a88fddd8cd04002

test:
  secret_key_base: 10cdb6cc1b2316d05c8986191f612cabff0c86dab306a1acef9c2188691002613c8146087fa689a735e003c8f502d05ef38887bcf7fd61ca67692e210e67b566

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
